# Generated by Django 5.0 on 2023-12-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=1000)),
                ("email", models.EmailField(max_length=1000)),
                ("subject", models.TextField()),
                ("message", models.TextField()),
            ],
        ),
    ]
